apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Usuario\Documents\kompose\kompose.exe --file docker-compose-dev-farma.yml
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: soporteayi/farma-frontend
        name: frontend
        ports:
        - containerPort: 80
        resources: {}
      nodeSelector:
        type: app
      restartPolicy: Always
status: {}
