apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Usuario\Documents\kompose\kompose.exe --file docker-compose-dev-farma.yml
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
  - name: "front"
    port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}

