---
- name: Deploy
  hosts: "manager-farma-dev"  
  remote_user: usr_deploy
  gather_facts: yes

  tasks:
  - name: Crear el directorio
    file:
     path: /opt/farmapago/FarmaFrontend
     state: directory

 # - name: Copiar el docker compose
 #   copy: 
 #    src: docker-compose-dev-farma.yml
 #    dest: /opt/farmapago/FarmaFrontend

 # - name: Deploy en Swarm
 #   shell: docker stack deploy -c /opt/farmapago/FarmaFrontend/docker-compose-dev-farma.yml farmapago
  - name: Update docker image
    shell: kubectl set image deployment frontend frontend=soporteayi/farma-frontend:{{ BUILD_NUMBER }}

- name: Clean Nodes
  hosts: "manager-farma-dev"
  remote_user: usr_deploy
  gather_facts: yes

  tasks:
  - name: limpiar containers
    shell: docker container prune -f

  - name: limpiar  imagenes
    shell: docker image prune -a -f

- name: Clean Nodes
  hosts: "nodo1-farma-dev"
  remote_user: usr_deploy
  gather_facts: yes

  tasks:
  - name: limpiar containers
    shell: docker container prune -f

  - name: limpiar  imagenes
    shell: docker image prune -a -f
      
  