FROM node as build-stage

RUN mkdir /app

WORKDIR  /app

COPY ./ /app/

RUN npm install

RUN npm install react-scripts@3.0.1 -g

RUN npm run build

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.15

COPY --from=build-stage /app/build /usr/share/nginx/html

COPY /devops/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

EXPOSE 443
